### PR TITLE
updating style to match mock-up, changing bg image, adding in animati…

### PR DESCRIPTION
**Pull request by pcsandford**
…on for up/down buttons

@mmeiers please review. Sorry this PR is so large, a lot is just deleting out commented code. I have added in keyframes and css for the button animation and changed text values to vw for responsiveness. Also added in a new bg image and styles to match the mock-up.

Thanks!

### CODE REVIEW

**Comment by mmeiers** [comment]
:+1: looks good
Could save you some room but you probably dont need any browser prefixes other than webkit but maybe its good measure to include incase someone previews in a different browser, thoughts?

**Comment by pcsandford** [comment]
@mmeiers good idea, I'm used to using the gulp autoprefixer to add those in but I didn't this time. I think it would be worth adding them going forwards, especially if the idea is that designers might be taking templates to build with and use as examples on on their own computers. Thanks!

**Comment by mmeiers** [comment]
@pcsandford I suppose my thought was that with rise preview it has a disclaimer that says best viewed in chrome and we only support chrome on your platform so was just wondering if the same would apply to templates.

But adding them in doesn't hurt i suppose, might be something we just bring up to @donnapep @stulees to get their thoughts at some point.

**Comment by donnapep** [comment]
@mmeiers @pcsandford I think we should include vendor prefixes so that we future-proof our templates. You never know what the future holds. We may end up moving away from Chrome altogether.

**Comment by pcsandford** [comment]
@donnapep @mmeiers really good point - an extra couple of seconds now could save a lot of searching around in the future. I have added them in for the next PR. Thanks!

**Comment by mmeiers** [comment]
@pcsandford @donnapep yep good point ill start adding them...

**Pull request merged**
